version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: wali-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: wali_livraison
      POSTGRES_USER: wali_user
      POSTGRES_PASSWORD: wali_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - wali-network-dev

  # Redis pour les sessions et cache
  redis:
    image: redis:7-alpine
    container_name: wali-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - wali-network-dev

  # Adminer pour la gestion de la base de données
  adminer:
    image: adminer
    container_name: wali-adminer-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - wali-network-dev

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  wali-network-dev:
    driver: bridge
